extends: standard
rules:
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  indent:
    - error
    - 4
  semi:
    - error
    - always
env:
  browser: true
